/**
 * Diet inference lexicons.
 *
 * These are CURATED LISTS, not patterns. A term is in a list or it isn't.
 * To fix a missed ingredient, add one line here — never edit matching logic.
 *
 * All terms must be lowercase, accent-free, and space-normalized (diacritics are stripped at runtime).
 * Multi-word terms are phrases; the matcher handles phrase matching (longest phrases win).
 */

// ---------------------------------------------------------------------------
// ANIMAL PRODUCTS — anything in here means the recipe is not vegan.
// Sub-categorized so we can also derive vegetarian / dairy-free.
// ---------------------------------------------------------------------------

export const ANIMAL_MEAT: string[] = [
  // red meat & pork
  'beef',
  'steak',
  'steaks',
  'veal',
  'pork',
  'ham',
  'bacon',
  'lard',
  'pancetta',
  'guanciale',
  'prosciutto',
  'capicola',
  'capocollo',
  'sausage',
  'salami',
  'pepperoni',
  'chorizo',
  'bratwurst',
  'kielbasa',
  'knockwurst',
  'bockwurst',
  'frankfurter',
  'frankfurters',
  'hot dog',
  'hotdog',
  'hot dogs',
  'wieners',
  'wiener',
  'weenies',
  'franks',
  'frank',
  'mince',
  'mincemeat',
  'ground beef',
  'ground pork',
  'ground lamb',
  'ground turkey',
  'ground chicken',
  'ground veal',
  'ground bison',
  'ground venison',
  'ground round',
  'ground chuck',
  'ground sirloin',
  'hamburger',
  'hamburger meat',
  'minced beef',
  'minced pork',
  'minced lamb',
  'minced turkey',
  'minced chicken',
  'chuck roast',
  'chuck steak',
  'pot roast',
  'standing rib',
  'brisket',
  'short rib',
  'short ribs',
  'spare rib',
  'spareribs',
  'spare ribs',
  'baby back ribs',
  'baby back rib',
  'st louis ribs',
  'st. louis ribs',
  'country style ribs',
  'back ribs',
  'side ribs',
  'rib tips',
  'ribs',
  'prime rib',
  'pork belly',
  'pork butt',
  'pork shoulder',
  'pork loin',
  'pork chop',
  'pork chops',
  'pork rind',
  'pork rinds',
  'cracklings',
  'tenderloin',
  'beef tenderloin',
  'pork tenderloin',
  'sirloin',
  'ribeye',
  'rib eye',
  'delmonico',
  'cowboy steak',
  'tomahawk',
  't-bone',
  't bone',
  'porterhouse',
  'tri-tip',
  'tri tip',
  'flank steak',
  'skirt steak',
  'hanger steak',
  'flat iron',
  'denver steak',
  'sirloin tip',
  'sirloin roast',
  'rump roast',
  'eye of round',
  'bottom round',
  'top round',
  'meatball',
  'meatballs',
  'meatloaf',
  'lamb',
  'lamb chops',
  'lamb rack',
  'lamb shank',
  'lamb leg',
  'lamb tongue',
  'mutton',
  'goat',
  'rabbit',
  'venison',
  'bison',
  'elk',
  'moose',
  'caribou',
  'wild boar',
  'boar',
  'antelope',
  'oxtail',
  'oxtails',
  'veal chops',
  'veal chop',
  'veal cutlet',
  'veal scaloppini',
  'tripe',
  'sweetbreads',
  'pastrami',
  'corned beef',
  'spam',
  'beef jerky',
  'jerky',
  'pulled pork',
  'pulled chicken',
  'suet',
  'tallow',
  'schmaltz',
  'ox tongue',
  'beef tongue',
  'bone marrow',
  'head cheese',
  'scrapple',
  'blood sausage',
  'moronga',
  'pheasant',
  'partridge',
  'grouse',
  'woodcock',
  'ostrich',
  'emu',
  'alligator',
  'crocodile',
  'snapping turtle',
  'frog legs',
  'frog leg',
  'snail',
  'snails',
  'escargot',
  // deli / charcuterie / misc cured
  'polish sausage',
  'andouille',
  'linguica',
  'linguicas',
  'bologna',
  'mortadella',
  'soppressata',
  'nduja',
  'speck',
  'cotechino',
  'liverwurst',
  // generic
  'meat',
  'meats',
];

export const ANIMAL_POULTRY: string[] = [
  'chicken',
  'chickens',
  'hen',
  'hens',
  'turkey',
  'turkeys',
  'duck',
  'ducks',
  'duckling',
  'goose',
  'geese',
  'quail',
  'squab',
  'cornish hen',
  'cornish game hen',
  'cornish game hens',
  'game hen',
  'game hens',
  'guinea fowl',
  'capon',
  'capons',
  'poultry',
  'chicken thigh',
  'chicken thighs',
  'chicken breast',
  'chicken breasts',
  'chicken wing',
  'chicken wings',
  'drumstick',
  'drumsticks',
  'giblets',
  'foie gras',
  'duck confit',
  'chicken liver',
  'chicken livers',
  'duck liver',
  'duck livers',
  'goose liver',
  'turkey liver',
  'turkey livers',
  'chicken gizzards',
  'chicken gizzard',
  'chicken hearts',
  'chicken heart',
];

export const ANIMAL_FISH: string[] = [
  'fish',
  'salmon',
  'tuna',
  'cod',
  'haddock',
  'tilapia',
  'trout',
  'bass',
  'perch',
  'halibut',
  'mackerel',
  'sardine',
  'sardines',
  'anchovy',
  'anchovies',
  'anchovy paste',
  'herring',
  'snapper',
  'catfish',
  'flounder',
  'sole',
  'mahi',
  'swordfish',
  'eel',
  'shrimp',
  'shrimps',
  'prawn',
  'prawns',
  'crab',
  'lobster',
  'clam',
  'mussel',
  'oyster',
  'scallop',
  'scallops',
  'squid',
  'calamari',
  'octopus',
  'crawfish',
  'crayfish',
  'caviar',
  'roe',
  'surimi',
  'fish sauce',
  'oyster sauce',
  'shrimp paste',
  'worcestershire',
  'worcestershire sauce',
  'seafood',
];

export const ANIMAL_DAIRY: string[] = [
  'milk',
  'cream',
  'butter',
  'cheese',
  'yogurt',
  'yoghurt',
  'ghee',
  'buttermilk',
  'curd',
  'paneer',
  'ricotta',
  'mozzarella',
  'parmesan',
  'cheddar',
  'feta',
  'brie',
  'gouda',
  'mascarpone',
  'creme fraiche',
  'half and half',
  'heavy cream',
  'whey',
  'casein',
  'custard',
  'condensed milk',
  'evaporated milk',
  'sour cream',
  'ice cream',
  'gelato',
];

export const ANIMAL_EGG: string[] = [
  'egg',
  'eggs',
  'egg white',
  'egg whites',
  'egg yolk',
  'egg yolks',
  'mayonnaise',
  'mayo',
  'meringue',
  'albumen',
];

// Animal-derived, not meat/fish/dairy/egg — clears vegan only (policy: also not vegetarian).
export const ANIMAL_OTHER: string[] = [
  'honey',
  'gelatin',
  'gelatine',
  'isinglass',
  'rennet',
  'carmine',
  'cochineal',
  'shellac',
  'bone broth',
  'beef stock',
  'beef broth',
  'chicken stock',
  'chicken broth',
  'turkey stock',
  'turkey broth',
  'fish stock',
  'fish broth',
  'veal stock',
  'veal broth',
  'lamb stock',
  'lamb broth',
  'duck fat',
  'bacon fat',
];

// ---------------------------------------------------------------------------
// PLANT OVERRIDES — contain an animal word but are NOT animal.
// Checked FIRST; claim their tokens so the animal word never matches.
// ---------------------------------------------------------------------------

export const PLANT_OVERRIDES: string[] = [
  'coconut meat',
  'jackfruit',
  'wheat meat',
  'nutmeg',
  'meaty mushroom',
  'butternut',
  'butter bean',
  'butter lettuce',
  'buttercup squash',
  'apple butter',
  'almond butter',
  'peanut butter',
  'cashew butter',
  'sunflower butter',
  'cocoa butter',
  'shea butter',
  'nut butter',
  'creamed corn',
  'cream of tartar',
  'cream of coconut',
  'coconut cream',
  'salad cream',
  'creamer',
  'milk thistle',
  'milkweed',
  'coconut milk',
  'soy milk',
  'almond milk',
  'oat milk',
  'rice milk',
  'cashew milk',
  'hemp milk',
  'pea milk',
  'eggplant',
  'eggplants',
  'egg-size',
  'egg-sized',
  'egg size',
  'egg noodle substitute',
  'fish pepper',
  'crab apple',
  'crabgrass',
  'oyster mushroom',
  'oyster sauce substitute',
  'chicken of the woods',
  'lambs lettuce',
  'lambs quarters',
  'lamb s quarters',
  'beefsteak tomato',
  'beefsteak tomatoes',
  'beef tomato',
  'sea vegetable',
];

// ---------------------------------------------------------------------------
// MEAT / DAIRY ALTERNATIVES — plant-based replacements.
// Checked FIRST; claim their tokens. Qualifier rules extend coverage (see matcher).
// ---------------------------------------------------------------------------

export const PLANT_ALTERNATIVES: string[] = [
  'beyond meat',
  'beyond beef',
  'beyond sausage',
  'beyond burger',
  'impossible',
  'impossible beef',
  'impossible burger',
  'tofurky',
  'tofurkey',
  'field roast',
  'gardein',
  'quorn',
  'seitan',
  'tempeh',
  'tofu',
  'textured vegetable protein',
  'tvp',
  'soy curls',
  'meatless',
  'mock duck',
  'mock meat',
  'facon',
  'vegan bacon',
  'nutritional yeast',
  'cashew cheese',
  'almond cheese',
  'soy cheese',
  'vegan cheese',
  'vegan butter',
  'plant butter',
  'oat creamer',
  'coconut yogurt',
  'soy yogurt',
  'almond yogurt',
  'cashew cream',
  'aquafaba',
  'flax egg',
  'chia egg',
  'egg replacer',
  'vegan mayo',
  'just egg',
  'chao',
  'miyokos',
  'daiya',
  'violife',
  'so delicious',
  'silk',
  'oatly',
  'ripple',
  'plant-based',
  'plant based',
  'plant-based chicken',
  'plant based chicken',
  'vegan chicken',
  'meatless meatballs',
  'vegan sausage',
  'soy chorizo',
  'imitation crab',
];

// Qualifier words: when one of these precedes ANY token, that token
// (and the qualifier) are claimed as plant.
export const PLANT_QUALIFIERS: string[] = [
  'vegan',
  'vegetarian',
  'plant-based',
  'plantbased',
  'meatless',
  'mock',
  'imitation',
  'faux',
  'fake',
  'vegetable-based',
  'soy',
];
